### ISSUE TITLE
Further byline changes in develop

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1259]
- [x] change 'Last modified' to 'Updated'
- [x] create ~~method in the Largo byline class~~ *generic conditional function* to check if a post has been updated, by diffing published and updated times
- [x] display normal `largo_time` published date if not `is_single()` or if it hasn't been updated
- [x] display updated date if it's been updated, even if not logged in

This extends #1126 somewhat

**Comment by aschweigert** [comment]
this is needed for rivard report

**Comment by benlk** [comment]
In bylines in single posts, are we moving the date down to the main byline, or are we only displaying the date in the main byline if it's the Updated date?

The current Largo behavior is to hide the published date with CSS: 
```css
body.normal.single-post article.post > header .sep,
body.normal.page article.post > header .sep,
body.normal.single-post article.page > header .sep,
body.normal.page article.page > header .sep,
body.normal.single-post article.post > header .entry-date,
body.normal.page article.post > header .entry-date,
body.normal.single-post article.page > header .entry-date,
body.normal.page article.page > header .entry-date {
    display: none;
}
```

This is the published date's html:

```html
<time class="entry-date updated dtstamp pubdate" datetime="2016-06-02T00:26:14+00:00"><span class="published">Published </span>June 2, 2016</time>
```

This is the updated date's html:

```html
<span class="last-modified">Updated June 2, 2016 at 11:29 pm</span>
```
