### ISSUE TITLE
Do these styles make sense? 

### ISSUE THREAD

**Issue by benlk** [INN/largo#1264]
``` css
body.normal.single-post article.post > header .sep,
body.normal.page article.post > header .sep,
body.normal.single-post article.page > header .sep,
body.normal.page article.page > header .sep {
    display: none;
}
```

Generated from [less/inc/single.less](https://github.com/INN/Largo/blob/d81cdfe4caa4790886ffea98d2e92decfc7cd06a/less/inc/single.less):

``` less
body.normal.single-post,
body.normal.page {

  /* 1.1 - Header */

  article.post > header,
  article.page > header {
    // a whole bunch of stuff
  } 

  // a whole bunch of some other stuff
}
```

Is there ever a possibility that there will be an `article.post > header` inside a `body.normal.page`, or a page header within a post?

These styles seem like they're creating two sets of spare CSS selectors for conditions that will never appear in use. Because of how LESS nesting works, we're creating rules for everything under those `> header` selectors, without them ever going to be used.

A slight reorganization of this section of the tile file is doable:

``` less
body.normal.single-post article.post > header,
body.normal.page article.page > header {
  /* 1.1 - Header */
  // a whole bunch of stuff

  }
}

body.normal.single-post,
body.normal.page {
  // a whole bunch of other stuff
}
```

This would remove the styles with these prefixes:

``` css
body.normal.page article.post > header
body.normal.single-post article.page > header 
```
