### ISSUE TITLE
Top term below 

### ISSUE THREAD

**Issue by benlk** [INN/largo#1472]
First reported in https://github.com/INN/umbrella-okwatch/issues/2

> There's a weird positioning thing with the top tag on article pages:
> It's only an issue on those narrow media queries, so please put the fix there!

Affecting browsers < 529px wide:

```css
body.normal.page article.page>header h5.top-tag,
body.normal.page article.post>header h5.top-tag,
body.normal.single-post article.page>header h5.top-tag,
body.normal.single-post article.post>header h5.top-tag {
    position: absolute;
    left: 0;
}
```

That's these lines: https://github.com/INN/largo/blob/v0.5.5.3/less/inc/single.less#L23-L27

Any fix should include a media query scoping that positioning to more than 529px, effectively the inverse  of https://github.com/INN/umbrella-okwatch/commit/e7b8826d6b4e49956bf6de4ff29486329a43d6cb

I believe this is caused by an `@media @mobile` query that contains styles affecting the spacing og the header, possibly https://github.com/INN/largo/blob/v0.5.5.3/less/inc/single.less#L122-L124
