### ISSUE TITLE
When set to show sticky nav at top of page, sticky nav doesn't

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1660]
The relevant setting is Theme Options > Navigation > 
"Hide the main navigation on article pages and display only the sticky navigation on article pages". 

The reason the sticky nav is not showing is because we aren't showing the sticky nav thoroughly enough.

https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/less/inc/navbar-sticky.less#L49-L51

It's set to display block, but the default state of `.sticky-nav-holder` is 

https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/less/inc/navbar-sticky.less#L8-L16

By default, it only shows up with the `.show` class, 

https://github.com/INN/largo/blob/72cc8433a1be1de4f22789e1ec89496d54a653d9/less/inc/navbar-sticky.less#L30-L33.

However, making the change to allow it to show at the top by default:

```less
  @media (min-width: 769px) {
    display: none;
    body &.main_nav_hide_article,
    body &.sticky_nav_display {
      display: block;
      visibility: visible;
      opacity: 1;
    }   
  }
```

means that it won't disappear on cue when scrolling farther down the page. 

What this really needs is the addition of `show` to the partial if it's in a `sticky_nav_display` situation, either through PHP or JS.
