### ISSUE TITLE
add alignfull image block caption rules to constrain caption width within main column

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1773]
Desired appearance:

![Screen Shot 2019-08-12 at 15 11 14 ](https://user-images.githubusercontent.com/1754187/62891464-c9d94b00-bd13-11e9-80fa-c96eca8a901b.png)

Present-day:

![Screen Shot 2019-08-12 at 15 11 34 ](https://user-images.githubusercontent.com/1754187/62891469-cf369580-bd13-11e9-9bc4-ccecdedf1a46.png)

the fix:

```css
.wp-block-image.alignwide figcaption,
.wp-block-image.alignfull figcaption {
   max-width: (the column width);
   margin: 0 auto;
}
```

will require testing on posts and pages using:

- [ ] one-column template
- [ ] mstoday's custom template
- [ ] two-column template
- [ ] fullwidth template
