### ISSUE TITLE
"Exit Clean Read" button is hidden by sticky nav

### ISSUE THREAD

**Issue by benlk** [INN/Largo#768]
On sites with sticky nav enabled and the "Clean Reading" feature enabled, the sticky nav will cover the fixed-position "Exit Clean reading" button.

Example: http://jjie.org/like-our-veterans-justice-involved-youth-are-survivors-of-war/108940/

![screen shot 2015-07-01 at 5 33 37 pm](https://cloud.githubusercontent.com/assets/1754187/8465339/5973e124-2017-11e5-83e8-29147b11c883.png)

In this image, the sticky nav's opacity has been set to 0.5

The clean-read button's syntax is 

    <a class="clean-read-close" href="#">Exit "Clean Read" mode</a>

And its position-related styles are in clean-read.less:

``` css
body.clean-read > .clean-read-close {
  position: fixed;
  top: 10px;
  right: 20px;
}
```
