### ISSUE TITLE
on mobile, top nav should clear the WP menu bar

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#808]
Right now it's partially obscured, see:

![mobile-nav](https://cloud.githubusercontent.com/assets/490703/8963970/013d110c-35f1-11e5-8a98-572687c950fa.png)

**Comment by benlk** [comment]
This is because WordPress doesn't change the margin-top it applies to `html` when it resizes the admin bar. :disappointed:

**Comment by aschweigert** [comment]
so are we just out of luck here?

**Comment by benlk** [comment]
My previous comment was wrong. Wordpress injects the following CSS if you're logged in:

```html
<style type="text/css" media="screen">
	html { margin-top: 32px !important; }
	* html body { margin-top: 32px !important; }
	@media screen and ( max-width: 782px ) {
		html { margin-top: 46px !important; }
		* html body { margin-top: 46px !important; }
	}
</style>
```

The positioning for the sticky nav in Largo is:

```css
body.admin-bar .sticky-nav-holder {
    top: 32px;
}
```

And largo adds a `logged-in` class to the `body` if you're logged in, so we could add a style:

```css
body.admin-bar.logged-in .sticky-nav-holder {
    top: 46px;
}
```
