### ISSUE TITLE
Remove margins from alignment utility classes

### ISSUE THREAD

**Issue by benlk** [INN/largo#819]
https://github.com/INN/Largo/blob/master/less/inc/wp-responsive-media.less#L12-L36:

``` less
.alignnone {
   margin: @baseline *0.75 0;
}

.aligncenter,
.align-center,
.center {
   clear: both;
   display:block;
   margin: (@baseline *0.75) auto;
}

.alignright,
.align-right,
.right {
   float:right;
   margin: @baseline/4 0 @baseline/2 20px;
}

.alignleft,
.align-left,
.left {
   float:left;
   margin: @baseline/4 20px @baseline/2 0;
}
```

The margins here should be applied to the image, or scoped more narrowly, not applied globally to the alignment utility classes.
