### ISSUE TITLE
Recheck module-wrapper styles for embeds when extracting properties from the embed

### ISSUE THREAD

**Issue by benlk** [INN/Largo#930]
```html
<aside class="module align-right extract type-embed">
    <iframe src="https://www.youtube.com/embed/ILVfzx5Pe-A" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen">
</iframe></aside>
```

This is the code generated when you do the following: 

1. paste a YouTube iframe embed code into the text editor,
2. in the visual editor select the iframe
3. Click the Module Wrapper button
4. Choose align-left, extract width, embed.
5. Save the post.
6. View the post.

<img width="974" alt="screen shot 2015-10-20 at 2 49 52 pm" src="https://cloud.githubusercontent.com/assets/1754187/10617705/dcfa6756-7739-11e5-893c-bfa4ec8f1653.png">

Removing this chunk of CSS causes the problem to disappear:

```css
.embed-container iframe, .embed-container object, .embed-container embed, .type-embed iframe, .type-embed object, .type-embed embed {
    position: absolute; */
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

This may be user error on my part, though.
