### ISSUE TITLE
LESS Customizer does not play well with data URIs.

### ISSUE THREAD

**Issue by benlk** [INN/largo#936]
While testing #923, I recompiled the LESS on JJIE. Instead of the expected:

``` css
.is-video {
  background-color: black;
  background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSc1JyBoZWlnaHQ9JzQgICAgJz48cGF0aCBpZD0ncGxheS10cmlhbmdsZScgZD0nTSAwIDAgTCAwIDQgTCA1IDIgTCAwIDAnIGZpbGw9J3doaXRlJyBzdHJva2U9J3doaXRlJyBzdHJva2Utd2lkdGg9JzAnLz48L3N2Zz4=");
  background-repeat: no-repeat;
  background-position: 50% 50%;
  background-size: 20%;
}
```

The following was included in the rendered CSS:

.is-video {
    background-color: black;
    background-image: url(//jjie.vagrant.dev/wp-content/themes/largo-dev/css/data:image/svg+xml;base6…AnIGZpbGw9J3doaXRlJyBzdHJva2U9J3doaXRlJyBzdHJva2Utd2lkdGg9JzAnLz48L3N2Zz4=);
    background-repeat: no-repeat;
    background-position: 50% 50%;
    background-size: 20%;
}

Note the addition of the `data:img/svg+ ...` with the path for CSS files in the parent theme: `//jjie.vagrant.dev/wp-content/themes/largo-dev/css/`
- [ ] regression test checking that `data` URIs are not prepended (would probably regex for passing `url(data:` and failing `url(//example.com/wp-content/themes/largo-dev/css/data:` )
