### ISSUE TITLE
Should article-bottom widgets have padding similar to sidebar widgets?

### ISSUE THREAD

**Issue by benlk** [INN/Largo#950]
<img width="769" alt="screen shot 2015-10-28 at 3 30 47 pm" src="https://cloud.githubusercontent.com/assets/1754187/10800586/f4615ab2-7d88-11e5-9348-d7d0b64e3a44.png">

The social icons in this screenshot inherit the following styles from the general `.widget` selector:

```css
.widget {
    padding: 0 24px;
    margin-bottom: 36px;
}
```

In this screenshot, the widget wraps because there is additional padding in the widget bottom that is not in the widget top.

Should we limit this padding-left and padding-right to the sidebar widgets?
